import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../app/theme.dart';
import '../brand/splash_screen.dart';

/// What to do when you cannot sign in.
///
/// This used to be a form: type your unit ID, and a request went into a queue
/// the office worked through. It is now a page that tells you who to ask.
///
/// The form looked like self-service and was not. Nothing it did could return
/// a password to the person who had lost one - a password is generated by the
/// office and read out or handed over, because that is the only step where
/// somebody confirms who they are talking to. So the request reached the same
/// person the phone number reaches, one queue later, while looking to the customer
/// like something had been done. Sending them straight to the office is the
/// same outcome, sooner, and honest about how it works.
class PasswordHelpScreen extends ConsumerWidget {
  const PasswordHelpScreen({super.key});

  // The one place these appear twice - here and on the login screen. Worth the
  // duplication over a settings round trip on a screen somebody reaches
  // because something is already not working.
  static const _phone = '+91 9876 543 210';
  static const _email = 'support@swarnim.in';

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      backgroundColor: SwarnimColors.navy,
      appBar: AppBar(
        backgroundColor: SwarnimColors.navy,
        elevation: 0,
        foregroundColor: SwarnimColors.inkOnDark,
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.fromLTRB(24, 8, 24, 32),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const Center(child: SwarnimLogo(width: 176)),
              const SizedBox(height: 28),

              Text(
                'Trouble signing in?',
                style: GoogleFonts.poppins(
                  fontSize: 19,
                  fontWeight: FontWeight.w600,
                  color: SwarnimColors.inkOnDark,
                ),
              ),
              const SizedBox(height: 10),
              Text(
                'Passwords are issued by the site office. Call or write to them '
                'and they will set a new one for you.',
                style: GoogleFonts.poppins(
                  fontSize: 13,
                  height: 1.5,
                  color: SwarnimColors.placeholderOnDark,
                ),
              ),

              const SizedBox(height: 24),
              const _Contact(label: 'Call the site office', value: _phone),
              const SizedBox(height: 12),
              const _Contact(label: 'Or email', value: _email),

              const SizedBox(height: 28),
              Text(
                'Have your username ready — residents use the unit ID on the '
                'allotment letter, and staff sign in with their mobile number. '
                'The office will confirm who you are before issuing a password.',
                style: GoogleFonts.poppins(
                  fontSize: 12,
                  height: 1.5,
                  color: SwarnimColors.metaOnDark,
                ),
              ),

              const SizedBox(height: 28),
              FilledButton(
                onPressed: () => context.go('/login'),
                child: const Text('Back to sign in'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

/// A label and a value, selectable so the number can be copied rather than
/// copied down onto paper.
class _Contact extends StatelessWidget {
  const _Contact({required this.label, required this.value});

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
      decoration: BoxDecoration(
        color: SwarnimColors.navyMid,
        borderRadius: BorderRadius.circular(SwarnimRadius.control),
        border: const Border(
          left: BorderSide(color: SwarnimColors.gold, width: 3),
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(label, style: SwarnimTheme.fieldLabelDark),
          const SizedBox(height: 4),
          SelectableText(
            value,
            style: GoogleFonts.poppins(
              fontSize: 15,
              fontWeight: FontWeight.w600,
              color: SwarnimColors.inkOnDark,
            ),
          ),
        ],
      ),
    );
  }
}
